[package]
name = "ticketing-app-1"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.7", features = ["json"] }
axum-server = { version = "0.7", features = ["tls-rustls"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tower-http = { version = "0.7.0", features = ["cors", "full"] }
dotenv = "0.15.0"
sqlx = {version = "0.8.6", features = ["sqlite", "runtime-tokio"]}
argon2 = "0.5.3"
axum-macros = "0.5.1"
jsonwebtoken = { version = "11.0.0", features = ["rust_crypto"] }
sha2 = "0.11.0"
base64 = "0.23.1"
rand = "0.10.2"
serde_json = "1.0.151"

